apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: jim-ihs-net-2
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: jim-ihs-net-2
spec:
  source:
    git:
      url: https://github.com/jimbaron/tanzulab
      ref:
        branch: master
  build: 
    env: 
      - name: BP_DOTNET_PROJECT_PATH
        value: ihs-net